name: Mirror FourVision Advanced HRM

on:
  schedule:
    - cron: '0 */5 * * *' # Every 5 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  mirror:
    if: github.ref_name != 'main' # Skip main branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Azure DevOps remote
        run: |
          git remote add azure https://dev.azure.com/FourVision/WebApps/_git/Hrm
          git fetch azure ${{ github.ref_name }} || echo "Branch not found in Azure, defaulting to master"
          if ! git show-ref --verify --quiet refs/remotes/azure/${{ github.ref_name }}; then
            git fetch azure master
            echo "AZURE_BRANCH=master" >> $GITHUB_ENV
          else
            echo "AZURE_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Mirror from Azure DevOps
        run: |
          git checkout -B ${{ github.ref_name }}
          git reset --hard azure/$AZURE_BRANCH
          git push origin ${{ github.ref_name }} --force
