name: Mirror FourVision Advanced HRM

on:
  schedule:
    - cron: '0 */5 * * *' # Every 5 hours
  workflow_dispatch:

permissions:
  contents: write # Required for pushing changes

jobs:
  mirror:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [master, Preview, Test, Int] # Add more branches here if needed
      max-parallel: 1  

    steps:
      - name: Checkout ${{ matrix.branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Azure DevOps remote
        run: |
          git remote add azure https://dev.azure.com/FourVision/WebApps/_git/Hrm
          if git ls-remote --heads azure ${{ matrix.branch }} | grep -q ${{ matrix.branch }}; then
            echo "Branch ${{ matrix.branch }} exists in Azure."
          else
            echo "::error::Branch '${{ matrix.branch }}' does not exist in Azure DevOps repository."
            exit 1
          fi
          git fetch azure ${{ matrix.branch }}

      - name: Mirror from Azure DevOps
        run: |
          git checkout -B ${{ matrix.branch }}
          git reset --hard azure/${{ matrix.branch }}
          git push origin ${{ matrix.branch }} --force
